# Gradle
org.gradle.jvmargs=-Dfile.encoding=UTF-8
org.gradle.caching=true

# Build plugins
spotlessPluginVersion=8.10.2
architecturyLoomPluginVersion=1.15.50
architecturyPack200PluginVersion=0.1.3
shadowPluginVersion=8.3.11
proguardVersion=7.10.0
foojayResolverPluginVersion=1.0.0

# Formatting
ktfmtVersion=0.64
licenseHeaderPath=license-header.txt
eclipseFormatterConfigPath=eclipse-formatter.xml

# Project
modId=pit12
modName=12pit
modVersion=0.1
modGroup=pit12

# Minecraft
loom.platform=forge
minecraftVersion=1.8.9
forgeVersion=11.15.1.2318-1.8.9
mappingsVersion=22-1.8.9

# Dependencies
minecraftGsonVersion=2.2.4
mixinRuntimeVersion=0.7.11-SNAPSHOT
mixinProcessorVersion=0.8.5-SNAPSHOT
devAuthVersion=1.2.2
archUnitVersion=1.5.0
javaWebSocketVersion=1.6.0
slf4jVersion=2.0.20
bouncyCastleVersion=1.86
